create table if not exists public.profiles (
  id text primary key,
  email text unique not null,
  full_name text default '',
  avatar_url text default '',
  auth_provider text not null default 'google',
  adopted_pet_count integer not null default 0,
  city text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists full_name text default '';
alter table public.profiles add column if not exists avatar_url text default '';
alter table public.profiles add column if not exists auth_provider text not null default 'google';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row
execute function public.set_updated_at();

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text unique not null check (name in ('admin', 'client', 'vet', 'sales'))
);

create table if not exists public.user_roles (
  user_id text not null references public.profiles(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  primary key (user_id, role_id)
);

create index if not exists idx_user_roles_user_id on public.user_roles(user_id);
create index if not exists idx_user_roles_role_id on public.user_roles(role_id);

insert into public.roles (name)
values ('admin'), ('client'), ('vet'), ('sales')
on conflict (name) do nothing;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null,
  is_active boolean not null default true
);

create table if not exists public.vet_services (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null,
  is_active boolean not null default true
);

create table if not exists public.adoptions (
  id bigint generated by default as identity primary key,
  pet_name text not null,
  user_id text not null references public.profiles(id),
  status text not null check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create or replace function increment_adopted_pet_count(profile_id text)
returns void
language plpgsql
security definer
as $$
begin
  update public.profiles
  set adopted_pet_count = adopted_pet_count + 1
  where id = profile_id;
end;
$$;
